version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile    # el Dockerfile optimizado de prod
    container_name: backend-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production